"""
CASEFILE data models package.

Contains all Pydantic models for:
- Agent contracts (requests/responses)
- Workflow state
- Budget tracking
- Checkpoints
- Phase 2 domain entities, contract envelope, and versioning
"""

from casefile.models.contracts import (
    BudgetState,
    Checkpoint,
    ClaimInput,
    ExtractionRequest,
    ExtractionResult,
    InvestigationRequest,
    InvestigationResult,
    ReviewRequest,
    ReviewResult,
    WorkflowResult,
    WorkflowState,
)
from casefile.models.domain import (
    ActorType,
    Address,
    AgentExecution,
    AgentType,
    ApprovalStatus,
    AuditEvent,
    AuditEventType,
    AuditResult,
    Claim,
    ClaimDocumentReference,
    ClaimPriority,
    ClaimStatus,
    ClaimType,
    CostAssessment,
    CoverageLimits,
    DamageEstimate,
    DamageLineItem,
    DocumentContentType,
    DocumentExtractionStatus,
    DocumentType,
    EvidenceItem,
    EvidenceSourceType,
    ExecutionStatus,
    FocusArea,
    FraudIndicator,
    FraudSeverity,
    HumanApproval,
    HumanApprovalRequest,
    InvestigationFindings,
    Money,
    Policy,
    PriorClaim,
    Recommendation,
    RecommendationType,
    RejectionDetails,
    ReviewFindings,
    ReworkPriority,
    ReworkRequest,
    RiskLevel,
    WorkflowRun,
)
from casefile.models.envelope import (
    HANDOFF_ROUTES,
    ContractEnvelope,
    ContractPayloadMismatchError,
    ContractType,
    HandoffRoute,
    UnknownContractTypeError,
)
from casefile.models.versioning import (
    ARTIFACT_VERSIONS,
    CURRENT_SCHEMA_VERSION,
    ArtifactVersions,
    IncompatibleSchemaVersionError,
    SchemaVersion,
    is_compatible,
    parse_version,
    validate_schema_version,
)

__all__ = [
    "ClaimInput",
    "ExtractionRequest",
    "ExtractionResult",
    "InvestigationRequest",
    "InvestigationResult",
    "ReviewRequest",
    "ReviewResult",
    "WorkflowResult",
    "WorkflowState",
    "BudgetState",
    "Checkpoint",
    "ActorType",
    "Address",
    "AgentType",
    "ApprovalStatus",
    "AuditEvent",
    "AuditEventType",
    "AuditResult",
    "Claim",
    "ClaimDocumentReference",
    "ClaimPriority",
    "ClaimStatus",
    "ClaimType",
    "CostAssessment",
    "CoverageLimits",
    "DamageEstimate",
    "DamageLineItem",
    "DocumentContentType",
    "DocumentExtractionStatus",
    "DocumentType",
    "EvidenceItem",
    "EvidenceSourceType",
    "ExecutionStatus",
    "FocusArea",
    "FraudIndicator",
    "FraudSeverity",
    "HumanApproval",
    "HumanApprovalRequest",
    "InvestigationFindings",
    "Money",
    "Policy",
    "PriorClaim",
    "Recommendation",
    "RecommendationType",
    "RejectionDetails",
    "ReworkPriority",
    "ReworkRequest",
    "ReviewFindings",
    "RiskLevel",
    "WorkflowRun",
    "AgentExecution",
    "ContractEnvelope",
    "ContractPayloadMismatchError",
    "ContractType",
    "HANDOFF_ROUTES",
    "HandoffRoute",
    "UnknownContractTypeError",
    "ARTIFACT_VERSIONS",
    "CURRENT_SCHEMA_VERSION",
    "ArtifactVersions",
    "IncompatibleSchemaVersionError",
    "SchemaVersion",
    "is_compatible",
    "parse_version",
    "validate_schema_version",
]
